[package]
name = "gurt-macros"
version = "0.1.0"
edition = "2021"
description = "Proc macros for Gurt: engine registration and routing attributes"
license = "MIT"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "parsing"] }